name = "cruise-news-digest"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "cruise-news-digest"
compatibility_flags = ["nodejs_compat"]

[env.preview]
name = "cruise-news-digest-preview"
compatibility_flags = ["nodejs_compat"]
